name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        export BUN_INSTALL="$HOME/.bun"
        export PATH="$BUN_INSTALL/bin:$PATH"
        source /home/runner/.bashrc 
        bun --version

    - name: Install dependencies
      run: bun install

    - name: Run tests
      run: bun test
      continue-on-error: true

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results

    - name: Create GitHub tag for test results
      if: failure()
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        TAG_NAME="test-failure-${TIMESTAMP}"
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git tag $TAG_NAME
        git push origin $TAG_NAME
